spring:
  application:
    name: devguy201.9-example

open:
  api:
    title: API-Service document
    version: v1.0.0
    description: description
    serverUrl: http://localhost:8080
    serverName: server test
