spring:
  application:
    name: devguy201.9-example
  profiles:
    active: @spring.profiles.active@

#To build use: mvn clean package -P dev
#To run use: java -jar .\target\devguy201.9-example-0.0.1-SNAPSHOT.jar
