server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    title: API-Service document
    version: v1.0.0
    description: description
    serverUrl: http://localhost:${server.port}
    serverName: server test
