server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod
openapi:
  service:
    title: API-Service document
    version: v1.0.0
    description: description
    serverUrl: http://localhost:${server.port}
    serverName: server test
